# Generated by Django 5.2.17 on 2026-09-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('item_type', models.CharField(choices=[('FILAMENTO', 'Filamento'), ('REPUESTO', 'Repuesto'), ('ACCESORIO', 'Accesorio')], default='FILAMENTO', max_length=20, verbose_name='tipo')),
                ('material', models.CharField(blank=True, choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('TPU', 'TPU'), ('OTRO', 'Otro')], max_length=20, verbose_name='material')),
                ('color', models.CharField(blank=True, help_text='Ejemplo: Carbón, Rojo vivo o Solar', max_length=40, verbose_name='color')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('tone', models.CharField(default='teal', help_text='teal, red, yellow, mist, graphite o steel', max_length=20, verbose_name='tono visual')),
                ('stock_label', models.CharField(default='En stock', max_length=40, verbose_name='estado de inventario')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('active', models.BooleanField(default=True, verbose_name='visible en la tienda')),
                ('featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-featured', 'name'],
            },
        ),
    ]
