# Generated by Django 5.2.17 on 2026-09-21 18:08

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Sube una foto de la caja, bobina o pieza. Mínimo 300 x 300 px.', null=True, upload_to='catalog/%Y/%m/', validators=[catalog.models.validate_catalog_image], verbose_name='imagen del producto'),
        ),
    ]
